# (d) Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: lab-fgm
---
# (a) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-fgm
  namespace: lab-fgm
  labels:
    app: backend-nest-test-fgm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-fgm
  template:
    metadata:
      labels:
        app: backend-nest-test-fgm
    spec:
      containers:
      - name: backend-nest-test-fgm
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-fgm
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
# (b) Service
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-svc
  namespace: lab-fgm
  labels:
    app: backend-nest-svc
spec:
  selector:
    app: backend-nest-test-fgm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
# (c) Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-fgm
  namespace: lab-fgm
spec:
  ingressClassName: nginx
  rules:
  - host: fgm.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-svc
            port:
              number: 80
